name: networkx
description: Custom network error types for easy error handling.
version: 0.1.1
homepage: https://github.com/elias8/networkx

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.1
