name: networkx
description: Custom network error types for easy error handling.
version: 0.2.0
homepage: https://github.com/elias8/networkx

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.2
